# rag configurations
MODEL_NAME: 'gpt-4'
CHUNK_SIZE: 512
CHUNK_OVERLAP: 10
TOP_K: 5


# path configurations
DATA_PATH: './data/'
VECTOR_STORE_PATH_LLAMA_INDEX: './vector_stores/chroma_db_llama_index'
VECTOR_STORE_PATH_LLANG_CHAIN: './vector_stores/chroma_db_lang_chain'

# streamlit configurations
TITLE: "Maroc Telecom Assistant"
ASSISTANT_MESSAGE: "Message IAM Assistance"
